/**
 * Writes `robots.txt` and `sitemap.xml` from `site-metadata.json`.
 *
 * Both files are generated rather than hand-written for the same reason the
 * metadata is centralized: a sitemap listing a page that no longer exists, or
 * missing one that does, is worse than no sitemap at all. Generating them from
 * the same list the router and the edge function read means they cannot disagree.
 *
 * Runs before `ng build` (see the `build:portfolio` script), writing into
 * `public/`, which the Angular build copies to the site root. The output is
 * committed so it is reviewable in a diff and so `ng serve` has it too.
 *
 *   node scripts/generate-seo.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = join(root, 'projects/portfolio/src/seo/site-metadata.json');
const publicDir = join(root, 'projects/portfolio/public');

const metadata = JSON.parse(readFileSync(source, 'utf8'));
const { origin, pages } = metadata;
const generatedBy = 'Generated by scripts/generate-seo.mjs — edit site-metadata.json instead.';

const urls = pages
  .map(page => `  <url><loc>${origin}${page.path}</loc></url>`)
  .join('\n');

// No lastmod: a date that is wrong is a date search engines learn to ignore, and
// nothing here knows when a page's content actually changed. No priority or
// changefreq either — Google has said for years that it reads neither.
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- ${generatedBy} -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

// Everything is allowed, including the AI crawlers, and that is the point: an
// assistant asked "who is Holly Johnson" can only answer from pages it may read.
// Nothing here is private — the unpublished pages are left out of the production
// bundle entirely (see unpublished.routes.ts), not hidden behind robots.txt.
const robots = `# ${generatedBy}

User-agent: *
Allow: /

Sitemap: ${origin}/sitemap.xml
`;

// Deno runs the edge function, and it resolves every import by exact file path:
// no Node-style extension guessing, and no JSON import without an attribute. The
// first version of this had the edge function import the app's `site-metadata.ts`
// directly and the deploy failed with:
//
//   Could not find file: /opt/build/repo/projects/portfolio/src/seo/site-metadata
//
// Angular cannot spell that import with a `.ts` extension (TS5096: it needs
// `noEmit`), so the two runtimes cannot share one module. They share the JSON
// instead, and this emits the Deno-shaped copy next to the function.
const generated = `// ${generatedBy}
//
// Deno resolves imports by exact file path, so the edge function cannot import
// the app's JSON or its extensionless modules. This is the same data, in the one
// shape Deno loads without argument. Do not edit; run the generator.

export const siteMetadata = ${JSON.stringify(metadata, null, 2)} as const;
`;

writeFileSync(join(publicDir, 'sitemap.xml'), sitemap);
writeFileSync(join(publicDir, 'robots.txt'), robots);
writeFileSync(join(root, 'netlify/edge-functions/lib/site-metadata.generated.ts'), generated);
console.log(`Wrote sitemap.xml (${pages.length} URLs), robots.txt, and the edge function's metadata copy`);
